### ISSUE TITLE
compile with hard serial on MKRZero

### ISSUE THREAD

**Issue by okvittem** [DFRobot/DFRobot_SIM7000#19]
I would like to use hardware serial on MKZero with a Simcom7020E modem.
However this library seem to be dependent on SoftSerial (which is not available on Arduino IDE 1.8.19).

**Comment by okvittem** [comment]
Sorry, the At commands for gprs and https on 7020 is way different from 7000 so I rest my case. I can't use this library anyhow.

**Comment by tangjie133** [comment]
This library is version-specific and not compatible.
